client/mock-entry.dev.js

This way we can keep the mock clean and closer to the result of the entry, source and meta-data loader

Use loader and examples of the plugin for the client.js development

---

client/components/ComponentPreview.js
client/components/Examples/index.js
client/components/Playground/index.js
examples/dev/src/components/button.js
package.json
plugin/component-loader.js
plugin/entry.js
plugin/examples-loader.js

IT WORKS!
But we should investigate how to drop Babel-standalone and compile the code in the backend with Babel.
@jantimon I ran into an issue here where Babel causes a loop or so. Maybe we can improve this together.

Render examples

---

client/components/Examples/index.js
examples/dev/src/components/immutableList.js
examples/dev/src/components/select.js
examples/dev/src/index.js

@jantimon two more examples to demonstrate what kind of fixtures we need.
I opend an issue for a more detailed discussion here: https://github.com/pure-ui/styleguide/issues/23

add more examples to figure out a useful example syntax

---

client/components/Playground/utils/getControl.js
plugin/__test__/normalize-meta-info.js
plugin/normalize-meta-info.js

@mxstbr I already merged it to continue. Please double check

fix edge case where the property is name type

---

client/components/Playground/ArrayControl/index.js
client/components/Playground/ObjectControl/index.js
client/components/Playground/utils/getControl.js
plugin/normalize-meta-info.js

@mxstbr here your beloved ObjectControl :smile: 
btw only for flow right now, the flow & proptype structure is quite different

More flow types

---

examples/dev/src/components/ghidorah.js

simplify-flow-example

---

plugin/server/server.js

Refactor current server routes to use the asynchronous variations of the `fs` methods.

Server update

---

client/components/MenuButton/styles.css
plugin/default-plugins/playground/frontend/components/Modal/index.js
plugin/default-plugins/playground/frontend/components/Modal/styles.css
plugin/default-plugins/playground/frontend/components/PlaygroundList/index.js
plugin/default-plugins/playground/frontend/components/PlaygroundList/styles.css
plugin/default-plugins/playground/frontend/components/PropForm/index.js
plugin/default-plugins/playground/frontend/components/PropForm/styles.css
plugin/default-plugins/playground/frontend/components/common/Input/styles.css
plugin/default-plugins/playground/frontend/components/common/Label/styles.css

- Modal is now a real modal with nice animation and that sort of thing
- Modal contents are now properly laid out

UX improvements

---

plugin/default-plugins/playground/frontend/components/PlaygroundList/index.js
plugin/default-plugins/playground/frontend/components/controls/ArrayControl/index.js

Enables batch updating and persisting to the server.
There's as of yet no indication of this happening in the UI itself, need to talk about how/where to do that!

Enable batch updates to avoid laggy UI

---

client/components/App/styles.css
plugin/default-plugins/playground/frontend/components/Playground/index.js
plugin/default-plugins/playground/frontend/components/Playground/styles.css
plugin/default-plugins/playground/frontend/components/PlaygroundList/index.js
plugin/default-plugins/playground/frontend/components/PlaygroundList/styles.css
plugin/default-plugins/playground/frontend/components/controls/ArrayControl/index.js

*This is just a concept, ignore the ugly button styling for now. Also, any color weirdness/flashes is due to `.gif` being a pain.*
What do you think?

Playground navigation concept

---

plugin/default-plugins/playground/frontend/components/controls/defaultControls.js
plugin/default-plugins/playground/frontend/utils/getControl.js

The CSS Modules currently prevent to export the defaultControls. We need to change the build process to to so.

Custom controls

---

istanbul.yml
mocha.opts
package.json
plugin/default-plugins/playground/frontend/utils/__test__/addDataToVariation.js

(see https://github.com/pure-ui/styleguide/issues/97)

Add Code Coverage

---

examples/dev/webpack.dev.babel.js
plugin/styleguide-plugin.js

Make custom, user-defined plugins work

---

plugin/default-plugins/playground/frontend/components/PlaygroundList/index.js
plugin/default-plugins/playground/frontend/utils/keycodes.js

Close Modal when ESC key is pressed

---

plugin/default-plugins/playground/plugin.js
plugin/default-plugins/playground/server/__test__/server.js
plugin/default-plugins/playground/server/run.js

I'm not a fan of the name `variationFolderName`, any better ideas?

Implement variationFolderName option for ReactPlugin

---

plugins/react/frontend/components/PlaygroundList/index.js
plugins/react/frontend/components/common/Playground/index.js
plugins/react/frontend/index.js
plugins/react/plugin.js
plugins/react/server/run.js

Fix fake stack traces

---

plugins/react/frontend/components/controls/base/ArrayControl/index.js

Updated ArrayControl to enable adding/removing entries 

---

client/components/App/index.js
client/components/Navigation/index.js
client/components/Navigation/styles.css
client/mock-entry.dev.js
plugins/react/frontend/components/PlaygroundList/index.js
plugins/react/frontend/utils/keycodes.js
utils/keycodes.js

Closes #172 
Added keyboard shortcuts, also added footer to general navigation to showcase keyboard shortcuts and information about the project:

Add keyboard shortcuts

---

plugins/react/frontend/components/controls/base/ArrayControl/ConstraintsForm/renderConstraintForm.js

Skip meta data values if none have been generated.

---

plugins/react/frontend/components/common/IFrame/index.js
plugins/react/frontend/components/common/Playground/index.js

TODO: Test if this actually fixes the issue

Fix card resizing

---

client/client.js
client/components/FourOhFour/index.js
client/components/Navigation/styles.css
plugins/react/frontend/components/PlaygroundList/index.js
plugins/react/frontend/components/PlaygroundList/styles.css
plugins/react/frontend/components/common/CreateVariationButton/index.js

- "Filter" field doesn't look like an input and more like a heading

update styles from #197

---

examples/redux/todomvc/package.json
examples/redux/todomvc/webpack.config.babel.js
plugins/react/frontend/components/PlaygroundList/index.js
plugins/react/frontend/components/common/IFrame/index.js
plugins/react/frontend/components/common/Playground/index.js
plugins/react/frontend/index.js
plugins/react/package.json
plugins/react/plugin.js

```JS
new ReactPlugin({
files: [ path.join(__dirname, './customStyles.js') ],
});
```
Does not work yet, because the CSS of the plugin doesn't get injected if you use this option, so I've disabled it for now. The groundwork is there though.

React plugin files option

---

package.json
plugins/react/frontend/components/CustomMetadataForm/controlTypes.js
plugins/react/package.json

This is a quick fix for the launch, the proper solution will be #210 but we need to work on the UI to make that happen for real.

Disable nested proptypes

---

plugins/react/frontend/components/PlaygroundList/index.js
plugins/react/frontend/components/common/IFrame/index.js
plugins/react/frontend/components/common/Playground/index.js
plugins/react/frontend/index.js
plugins/react/plugin.js

```JS
new ReactPlugin({
injectTags: [
'<link href="domain.com/myexternal.css" rel="stylesheet" />'
],
}),
```

Implement injectTags option in ReactPlugin

---

webpack-plugin/src/apply.js
webpack-plugin/src/utils/__test__/createHTML.js
webpack-plugin/src/utils/createHTML.js
webpack-plugin/src/validateOptions.js

Fixes #232, also fixes dest option

Fix dest option and /carte-blanche/ (trailing slash)

---

plugins/react/frontend/components/PlaygroundList/index.js
plugins/react/frontend/components/common/IFrame/index.js
plugins/react/frontend/components/common/Playground/index.js
plugins/react/frontend/index.js
plugins/react/package.json
webpack-plugin/src/apply.js
webpack-plugin/src/dynamic-resolve.js
webpack-plugin/src/loaders/plugins-loader.js

Pass `dest` through to iframe so they refer to the correct bundles

Fix iframes with dest option

---

CONTRIBUTING.md
README.md

Getting everything ready for launch. Don't merge yet!

README update

---

package.json

added exenv to dependencies

---

plugins/react/plugin.js

fix react-plugin port parse validation.

---

client/components/Navigation/styles.css

- Scroll in navigation does not work.
- Unreadable info when you have a lot of components.

Fix navigation scroll and info box background.

---

client/components/App/index.js

Fix keyboard shortcuts

---

README.md

Probably a better place to put this and better way to write it, but figured I'd start!

Document examples

---

examples/express/package.json
examples/express/src/components/Button/index.js
examples/express/src/components/Button/styles.js
examples/express/src/components/Profile/index.js
examples/express/src/components/Profile/styles.js
examples/express/src/index.html
examples/express/src/index.js
examples/express/src/server.js
examples/express/src/styles.js
examples/express/webpack.dev.babel.js
package.json
webpack-plugin/src/apply.js

Express integration

---

plugins/react/frontend/utils/__test__/codeToCustomMetadata.js

The test was failing locally but not on Travis (probably due to different versions of Node).
I hope it's the correct way to fix it.

fixed assertion

---

examples/library/.gitignore
examples/library/Makefile
examples/library/package.json
examples/library/src/components/Button.js
examples/library/src/components/index.js
examples/library/src/containers/Foobar.js
examples/library/src/containers/Root.js
examples/library/src/index.foobar.js
examples/library/src/index.js
examples/library/webpack.config.js
examples/library/webpack.config.prod.js
package.json
webpack-plugin/src/apply.js

Closes #321 
Thanks @tmc for the repro!

Support libraries

---

README.md

Reference https://github.com/carteb/carte-blanche/issues/348#issuecomment-228267845

Add the react@15 requirement to README

---

plugins/react/frontend/components/common/IFrame/index.js

just a small improvement to make the component vertically aligned inside the iframe

set iframe content height to 100vh to align vertically the content

---

plugins/react/frontend/components/common/Button/index.js
plugins/react/frontend/components/common/Button/styles.css
plugins/react/frontend/components/common/DeleteButton/index.js
plugins/react/frontend/components/common/DeleteButton/styles.css
plugins/react/frontend/components/common/EditButton/index.js
plugins/react/frontend/components/common/EditButton/styles.css
plugins/react/frontend/components/common/Playground/index.js
plugins/react/frontend/components/common/RefreshButton/index.js
plugins/react/frontend/components/common/RefreshButton/styles.css

Added a new refresh button to the interface that un- and remounts the iframe. It's quite slow, maybe there's a better way to do this?
I also took the opportunity and refactored the buttons to use a common button component and styles.

Refresh components support
