plugin/default-plugins/playground/frontend/components/controls/ArrayControl/index.js
plugin/default-plugins/playground/frontend/components/controls/BooleanControl/index.js
plugin/default-plugins/playground/frontend/components/controls/IntegerControl/index.js
plugin/default-plugins/playground/frontend/components/controls/ObjectControl/index.js
plugin/default-plugins/playground/frontend/components/controls/StringControl/index.js
plugin/default-plugins/playground/frontend/utils/getControl.js
plugin/default-plugins/playground/frontend/utils/randomValues.js
plugin/default-plugins/playground/frontend/utils/valueOrNullOrUndefined.js

Previously, even prop types like `PropTypes.string.isRequired` generated `null` and `undefined` on random generation, which they shouldn't.
This is a RFC because I'm not sure the signature for the `randomValues` function makes sense. I changed it to:
```JS
Control.randomValue = (props) { /* … */ }
/* …or, for Array and Object controls… */
Control.randomValue = (propTypeValue) { /* … */ }
```
This `props`/`propTypeValue` argument has an `required` property, which is injected in `utils/getControls.js` for each component.
Every control is aware of the fact that it can or cannot generate null or undefined. This should be overrideable in the admin interface, which is why I still re-determine it on every `randomValue()` call.
Maybe it makes more sense to change the function signature to …

RFC: required propTypes no longer generate null and undefined

---

plugin/default-plugins/playground/frontend/components/Playground/index.js
plugin/default-plugins/playground/frontend/components/Playground/styles.css
plugin/default-plugins/playground/frontend/components/common/DeleteButton/index.js
plugin/default-plugins/playground/frontend/components/common/DeleteButton/styles.css
plugin/default-plugins/playground/frontend/components/common/EditButton/index.js
plugin/default-plugins/playground/frontend/components/common/EditButton/styles.css

Hovering over the card, there's a slight delay before the buttons show so it doesn't become really annoying when scrolling.
When directly hovering over the buttons though, the delay is removed and the buttons can immediately be clicked. :+1:

Improve playground ui experience

---

client/components/Navigation/index.js
plugin/default-plugins/playground/frontend/components/Playground/index.js
plugin/default-plugins/playground/frontend/components/PlaygroundList/index.js
utils/getStylingNodes.js

Component styling injection works now! :fire:
There's one problem with it, everytime you go to a new component the style tags of that component are added, but **the old style tags are not removed**. I.e. after a while you end up with 100000s of style tags in a) the DOM and b) all the iFrames, which doesn't seem very healthy:
_This was taken after clicking back and forth between the Button and the ImmutableList about 5 times_

Component styling injection

---

plugin/default-plugins/playground/frontend/components/Playground/index.js
plugin/default-plugins/playground/frontend/components/Playground/styles.css

@mxstbr @nikgraf have a look at my first pretty straight forward implementation.  i think there is not much to explain.
i used a dirty workaround to access the `Frame` and `Card` element because refs dont work (https://github.com/pure-ui/styleguide/issues/126). once they work we should replace the `reactDOM.findDOMNode(this)` thing.

Proper component cards resizing

---

examples/dev/webpack.dev.babel.js
plugin/default-plugins/playground/frontend/components/PlaygroundList/index.js
plugin/default-plugins/playground/frontend/index.js
plugin/default-plugins/playground/plugin.js
plugin/default-plugins/playground/server/__test__/server.js
plugin/default-plugins/playground/server/run.js
plugin/default-plugins/playground/server/server.js
plugin/meta-loader.js
plugin/styleguide-plugin.js

You can now start the ReactPlugin on different hostnames and ports:
```JS
new ReactPlugin({
port: 6500,
hostname: 'example.com',
})
```

Make hostname and port option of ReactPlugin work

---

examples/aphrodite/src/components/Button/index.js
examples/aphrodite/src/components/Button/styles.js
examples/aphrodite/src/components/Profile/index.js
examples/aphrodite/src/components/Profile/styles.js
examples/aphrodite/src/index.html
examples/aphrodite/src/index.js
examples/aphrodite/webpack.dev.babel.js
package.json

For some reason the styling of the components in the Styleguide is applied sometimes, but not always:
These two screenshots show the same variation, but in the Modal the styles are applied, in the Card they aren't…
Maybe the same problem as with JSS styles?
Closes #139

Add aphrodite example

---

plugin/default-plugins/playground/frontend/components/common/Input/index.js
plugin/default-plugins/playground/frontend/components/common/Label/index.js
plugin/default-plugins/playground/frontend/components/common/Label/styles.css
plugin/default-plugins/playground/frontend/components/common/Select/index.js
plugin/default-plugins/playground/frontend/components/controls/advanced/AvatarControl/index.js
plugin/default-plugins/playground/frontend/components/controls/advanced/NameControl/index.js
plugin/default-plugins/playground/frontend/components/controls/base/BooleanControl/__test__/index.js
plugin/default-plugins/playground/frontend/components/controls/base/BooleanControl/index.js
plugin/default-plugins/playground/frontend/components/controls/base/EnumControl/__test__/index.js
plugin/default-plugins/playground/frontend/components/controls/base/EnumControl/index.js
plugin/default-plugins/playground/frontend/components/controls/base/FunctionControl/index.js
plugin/default-plugins/playground/frontend/components/controls/base/IntegerControl/__test__/index.js
plugin/default-plugins/playground/frontend/components/controls/base/IntegerControl/index.js
plugin/default-plugins/playground/frontend/components/controls/base/StringControl/__test__/index.js
plugin/default-plugins/playground/frontend/components/controls/base/StringControl/index.js
plugin/default-plugins/playground/frontend/utils/renderControls.js

The form now shows the original propType in the PropForm UI:
I originally wanted to show `customPropType (originalPropType)` (e.g. `name (node)`), but I don't have access to the name of the chosen control in `renderControls`, which means I can't display it.
Any ideas how to pipe that through are much appreciated, but if not this should be fine!
I also added tests for the new secondary label, but didn't spend too much time tinkering with the styling since that's going to change with #145 anyway.
Closes #133

Show original propType in PropForm

---

plugins/react/frontend/components/PlaygroundList/index.js
plugins/react/frontend/components/common/Playground/index.js
plugins/react/frontend/components/common/Playground/styles.css
plugins/react/frontend/utils/__test__/variationsToProps.js
plugins/react/frontend/utils/getVariationComponentPath.js
plugins/react/frontend/utils/variationsToProps.js

Properly catch and handle individual variation parsing errors.
The remaining app remains usable, only the variation that the parsing failed of shows a stack trace:

Handle variation parsing errors

---

plugins/react/frontend/components/PlaygroundList/index.js
plugins/react/frontend/components/PlaygroundList/styles.css
plugins/react/frontend/utils/__test__/codeToCustomMetadata.js
plugins/react/frontend/utils/__test__/variationsToProps.js
plugins/react/frontend/utils/codeToCustomMetadata.js

Not only shows the error, also gives a nicely usable stack trace and recovers from errors perfectly fine!

Handle metadata parsing error

---

WRITING-PLUGINS.md
plugins/react/frontend/index.js
plugins/react/plugin.js
webpack-plugin/plugins-loader.js

- First draft of the first part of the docs on how to write a plugin (unfinished because changes incoming due to the things I've realised while writing this)
- `frontendPlugin` of plugins now has signature `plugin(frontendData, pluginData, Component, componentPath)` instead of `plugin(options, data, Component, componentPath)`. (`options` was just `frontendData.options`, we should pipe the whole thing through)
- Rename `renderToStyleguide` to `renderToClient`
- Rename data to pluginData in webpack part
- Allow plugins to not pass any `frontendData` (previously we filtered all plugins that had none)

Even more cleanup

---

plugins/react/plugin.js

Error messages weren't shown because the ReactPlugin halted exiting, but then didnt log the errors.

Fix process exit

---

plugins/react/frontend/components/PlaygroundList/index.js
plugins/react/package.json

`whatwg-fetch` is a very intrusive polyfill for `window.fetch` that doesn't work in some environments (e.g. my boilerplate), so I switched it out and now use axios which is very similar. (imo better because more developer friendly)

Remove fetch, replace it with axios

---

webpack-plugin/src/validateOptions.js

Webpack has no protection against inserting */ in the comments it writes when output.pathinfo is true

Fix webpack regex embed comment termination

---

plugins/react/frontend/components/common/CreateVariationButton/index.js

Currently `onBlur` the add variant form disappears. This is especially irritating when you click "Add Variant" and nothing happens. The easiest solution I could think of was just adding a "cancel" button.
Before:
After:

Fix "Create Variant" button

---

plugins/react/frontend/components/PropForm/index.js
plugins/react/frontend/components/form/ComboBox/styles.css
plugins/react/frontend/components/form/Dropdown/styles.css
plugins/react/frontend/components/form/Grid/LeftColumn/styles.css
plugins/react/frontend/components/form/Grid/RightColumn/styles.css
plugins/react/frontend/components/form/Grid/styles.css

The problem(s):
- Form bleeding into right edge of form due to `scroll-y` requirement of container.
- Dropdown & ComboBox offset by their widths, forcing the user to scroll if they want to set a prop val to null or undefined.
Minor fixes in the styles to fix these.

Fix PropForm styles

---

plugins/source/plugin.js

I have to access to `default` property
```js
const SourcePlugin = require('carte-blanche-source-plugin').default;
```

fix source plugin export

---

README.md
webpack-plugin/src/validateOptions.js

Currently the component filter will match a file that contains a capital letter. This matches files such as
`allReducers.js`
Updated so that the file and/or directory needs to start with capital letter. eg, `Button.js` or `Button/index.js`
Tested the base cases - not sure of the impact on the system of requiring a leading forward slash. Seems ok.

Look for components starting with a capital letter

---

examples/commons/src/components/Button/index.js
examples/commons/src/components/Button/styles.js
examples/commons/src/components/Profile/index.js
examples/commons/src/components/Profile/styles.js
examples/commons/src/index.html
examples/commons/src/index.js
examples/commons/src/styles.js
examples/commons/webpack.dev.babel.js
package.json
plugins/react/frontend/components/PlaygroundList/index.js
plugins/react/frontend/components/common/IFrame/index.js
plugins/react/frontend/components/common/Playground/index.js
plugins/react/frontend/index.js
webpack-plugin/src/apply.js
webpack-plugin/src/dynamic-resolve.js
webpack-plugin/src/loaders/plugins-loader.js
webpack-plugin/src/utils/__test__/constructorIndexInArray.js
webpack-plugin/src/utils/__test__/createHTML.js
webpack-plugin/src/utils/constructorIndexInArray.js
webpack-plugin/src/utils/createHTML.js
webpack-plugin/src/utils/getCommonsChunkFilename.js

This PR adds implicit (!) `CommonsChunkPlugin` support and an example with the plugin enabled.
That means we auto-detect if users use it and adapt to it by including the common chunk into our HTML files. No config needed™!
:tada:
*Note: We check if users have it included by checking the constructor name in the plugins array. This means if people do something weird like `import CommonsChunkPlugin as SomethingElse` and then do `new SomethingElse()` in their plugins array, it won't work, but honestly we should discourage that anyway.*
Two small points-of-action we should do after this is merged:
- We should find a better (i.e. more scalable) way to pipe specific data from the core options to the plugins (like right now the `dest` option and the `commonsChunkFilename`), but that's for another …

CommonsChunkPlugin support

---

.gitignore
client/client.js
client/iframe-client.js
client/webpack.prod.babel.js
plugins/react/frontend/components/common/IFrame/index.js
webpack-plugin/src/apply.js

Until now we both parts where part of the client and just determined on a condition.
The idea here is for once to have cleaner setup, but also to improve the execution time. Unfortunately this will bring just save us around 50 milliseconds per iFrame (on my machine).
Previous loading results with client & iframe client combined:
Loading results with client & iframe client being separate:
The big chunk definitely is the user-bundle with the app inside taking up around 700milliseconds to evaluate:
Even in our dev example the file-size of the user-bundle is already quite large with 9.6 MB

Split client into client and iframe client

---

plugins/react/frontend/components/common/Playground/styles.css
plugins/react/frontend/components/form/Grid/styles.css

When the props modal was shown, the columns wouldn't stretch to 100% height of the window. That caused dropdowns not showing properly if they were in the last row:
This fix makes both columns (props and preview) scrollable independently and sets their wrapper to fit the window.

Fix prop sidebar in modal form to be full height of the window

---

plugins/react/frontend/components/controls/advanced/AvatarControl/randomValue.js
plugins/react/frontend/components/controls/advanced/IntegerControl/randomValue.js
plugins/react/frontend/components/controls/advanced/NameControl/randomValue.js
plugins/react/frontend/components/controls/advanced/PhoneControl/randomValue.js
plugins/react/frontend/components/controls/base/StringControl/randomValue.js

fixes #336 
I haven't noticed any problem with my edits, the data is correctly randomized.
Tests fail with:
```
1) codeToCustomMetadata should catch errors correctly:
AssertionError: expected { Object (err) } to deeply equal { Object (err) }
+ expected - actual
{
-  "err": "SyntaxError: Unexpected token u in JSON at position 26"
+  "err": "SyntaxError: Unexpected token u"
}
at Assertion.assertEqual (plugins/react/node_modules/chai/lib/chai/core/assertions.js:485:19)
at Assertion.ctx.(anonymous function) [as equal] (plugins/react/node_modules/chai/lib/chai/utils/addMethod.js:41:25)
at Context.<anonymous> (codeToCustomMetadata.js:34:48)
```
But it fails even on master, so I don't think it's related to this PR

use source of faker instead of compiled one

---

package.json

Was checking out the project and was trying to get the examples to run when I ran into this problem:
```bash
npm install
> carte-blanche-react-plugin@0.3.0 build:backend /projects/carte-blanche/plugins/react
> cross-env BABEL_DISABLE_CACHE=1 BABEL_ENV=production babel --out-dir=dist plugin.js resolver.js server/server.js server/run.js server/utils/getAbsoluteVariationPath.js
You have mistakenly installed the `babel` package, which is a no-op in Babel 6.
Babel's CLI commands have been moved from the `babel` package to the `babel-cli` package.
npm uninstall babel
npm install babel-cli
See http://babeljs.io/docs/usage/cli/ for setup instructions.
```
This change simply removes the `babel` package which is a no-op in Babel 6. Removing it makes the `npm install` process not error out anymore. …

Remove no-op babel package from package.json
